import Head from 'next/head';
import { FunctionComponent } from 'react';

const Home: FunctionComponent = () => {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  );
};

export default Home;
