import Head from "next/head";
import { FunctionComponent } from "react";

const BlogIndex: FunctionComponent = () => {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </div>
  );
};

export default BlogIndex;
