import Head from "next/head";
import router, { useRouter } from "next/router";
import { FunctionComponent } from "react";
import { makeStyles } from "@material-ui/core/styles";
import backGroundImage from "../../public/Diphyll.png"
import copyImage1 from "../../public/copy1.png"
import noticeImage from "../../public/notice.png"
import noNameGirlImage from "../../public/nonamegirl.png"
import Image from "next/image";
import getConfig from 'next/config'

const backgroundColor = "#F1F0E5";

const useStyles = makeStyles(() => ({
  pos:{
    position:"relative",
    width:"100%",
    height:"100%"
  },
  background: {
    position:"absolute",
    height:"100%",
    width:"100%",
    zIndex:1
  },
  copy: {
    position:"absolute",
    width:"20%",
    height:"20%",
    right:"30vh",
    top:"30vh",
    zIndex:2
  },
  notice:{
    position:"absolute",
    width:"30%",
    height:"30%",
    right:"20vh",
    top:"40vh",
    zIndex:2
  },
  nonamegirl:{
    position:"absolute",
    width:"30%",
    height:"30%",
    left:"20vh",
    top:"0.2vh",
    zIndex:2
  }
}));

const Home: FunctionComponent = () => {
  const classes = useStyles();
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@Diphyl_Grayi" />
        <meta name="twitter:title" content="Diphylleia" />
        <meta name="twitter:description" content="Next fall, bloom❁" />
        <meta property="og:image" content={`${process.env.SITE_URL}/preview.png`} />
        <meta name="twitter:card" content="summary_large_image"/>
      </Head>
      <div className={classes.background}>
        <Image src={backGroundImage} alt="" />
        <div className={classes.copy}>
          <Image src={copyImage1} alt="" />
        </div>
        <div className={classes.notice}>
          <Image src={noticeImage} alt="" />
        </div>
        <div className={classes.nonamegirl}>
          <Image src={noNameGirlImage} alt="" />
        </div>
      </div>
    </div>
  );
};

export default Home;
